# Generated by Django 4.1.5 on 2023-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_cmsslider_cms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(upload_to='slidering/'),
        ),
    ]
